# DB \uc811\uc18d \uc815\ubcf4 (MariaDB 11)
Globals.DriverClassName=org.mariadb.jdbc.Driver
Globals.Url=jdbc:mysql://192.168.10.37:2205/hcnc_team07A
Globals.UserName=hcnc_team07A
Globals.Password=1234